### ISSUE TITLE
Can't install on os-x mavericks 10.9 

### ISSUE THREAD

**Issue by JustinSGray** [arunoda/laika#104]
When trying sudo npm install -g laika i get: 

gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/Cellar/node/0.10.21/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:424:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 13.0.0
gyp ERR! command "node" "/usr/local/Cellar/node/0.10.21/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/laika/node_modules/fibers
gyp ERR! node -v v0.10.21
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok

**Comment by JustinSGray** [comment]
I had to do the following 

```
npm cache clean
```

Then I had to install the full Xcode. I had the Xcode command line tools installed. But apparently thats not enough.
