### ISSUE TITLE
Laika on Windows

### ISSUE THREAD

**Issue by zs-zs** [arunoda/laika#108]
On Windows, when I try to run the tests for the [hello-laika](https://github.com/arunoda/hello-laika) sample I get the following error:

```
injecting laika...
loading phantomjs...
cleaning up injected code


C:\Users\...\AppData\Roaming\npm\node_modules\laika\lib\app.js:130
    if(err) throw err;
                  ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
```
- I have the latest Laika (0.3.8) installed from npm.
- I have the latest version of PhantomJS
- I have the latest version of Meteor installed.

(Tested on Windows 8.1)

It seems that it can't start the Meteor server, but I haven't taken any further investigations.
Maybe I misconfigured something...(?)

Both the PhantomJS and the Meteor are available on my PATH.

**Comment by zs-zs** [comment]
Oh I guess it's because on Windows Meteor is a batch file, so you have to start it with meteor.bat, or something like this...

**Comment by andyp22** [comment]
I was having this problem and the solution posted by zs-zs in https://github.com/arunoda/laika/pull/110 worked for me.
