### ISSUE TITLE
Laika broke with 0.8.1

### ISSUE THREAD

**Issue by AdamBrodzinski** [arunoda/laika#117]
After i've updated my app to 0.8.1.1, my tests hang and timeout. I can make them pass by changing `.meteor/release` to 0.8.0.1. From what I can tell, it's only affected by the client tests.

I've also replicated this by cloning down hello-laika. I pasted the output below:

```
hello-laika-master|⇒ laika -v
0.3.9
hello-laika-master|⇒ laika

  injecting laika...
  loading phantomjs...
  loading initial app pool...


  Posts
    ✓ in the server
    ✓ using both client and the server
    ✓ using two clients


  3 passing (981ms)

  cleaning up injected code
```

```
hello-laika-master|⇒ meteor update
hello-laika-master: updated to Meteor 0.8.1.1.

-- Notice --

0.8.0: Meteor has a new live templating engine: Blaze!
       See https://github.com/meteor/meteor/wiki/Using-Blaze for what's new.
```

```
hello-laika-master|⇒ laika

  injecting laika...
  loading phantomjs...
  loading initial app pool...


  Posts
    ✓ in the server
    ✓ using both client and the server
    1) using two clients


  2 passing (5s)
  1 failing

  1) Posts using two clients:
     Error: timeout of 5000ms exceeded
      at null.<anonymous> (/usr/local/lib/node_modules/laika/node_modules/mocha/lib/runnable.js:175:14)
      at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)



  cleaning up injected code
```

_change release back to 0.8.0.1_

```
hello-laika-master|⇒ vim .meteor/release
hello-laika-master|⇒ laika

  injecting laika...
  loading phantomjs...
  loading initial app pool...


  Posts
    ✓ in the server
    ✓ using both client and the server
    ✓ using two clients


  3 passing (845ms)

  cleaning up injected code
```

I hope this helps!

**Comment by AdamBrodzinski** [comment]
Perhaps this is from a [change](https://github.com/meteor/meteor/blob/devel/History.md#upgraded-dependencies) with 'css-stringify'.

**Comment by Linskeyd** [comment]
Hey Adam please take a look at issue #77 that was closed a while ago.  I wonder if third test failing is related to this somehow?  Adding in server side evals which do nothing on each test that uses only client calls allows the tests to pass, but they take around 1.3 seconds to complete which is pretty long.

**Comment by AdamBrodzinski** [comment]
@Linskeyd I just tried that but it doesn't make a difference.

However.... while trying that, one time I started up `mongod` without the `--smallfiles --noprealloc --nojournal` and they all passed :smile: Thanks!

passing:
`mongod`

client tests fail:
`mongod --smallfiles --noprealloc --nojournal`

**Comment by Linskeyd** [comment]
@AdamBrodzinski It worked for me too!!  Thanks :smile:
