### ISSUE TITLE
laika couldn't run in meteor app

### ISSUE THREAD

**Issue by toitoi** [arunoda/laika#155]
C:\Users\xxx\meteor_proj\meteor-base-blaze-boilerplate>laika -V
[laika log] accepting the following extensions: (js)

injecting laika...
loading phantomjs...
cleaning up injected code

C:\Users\xxx\AppData\Roaming\npm\node_modules\laika\lib\app.js:124
if(err) throw err;
^

Error: spawn meteor ENOENT
at exports._errnoException (util.js:856:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
at onErrorNT (internal/child_process.js:344:16)
at doNTCallback2 (node.js:452:9)
at process._tickCallback (node.js:366:17)

Hi, i just couldn't get laika running in my meteor app, 
-> windows 8.1
-> laika 0.3.10
-> phantomjs 2.0.0
-> meteor 1.2.1

**Comment by apendua** [comment]
Laika is no longer actively maintained. Would you consider using Gagarin
instead? It has a good windows support.

W dniu czwartek, 19 listopada 2015 SK. Ng notifications@github.com
napisał(a):
