### ISSUE TITLE
Module version mismatch

### ISSUE THREAD

**Issue by subhog** [arunoda/laika#18]
When I run `laika` commmand, I'm greeted with four such error messages:

```
nodetime v0.8.12 error: [Error: Module version mismatch. Expected 11, got 1.] Error: Module version mismatch. Expected 11, got 1.
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/Users/hubert/.meteorite/packages/nodetime/subhog/meteor-nodetime/71c155845b4d0c99ba471d1498d113cef499dbd6/.npm/node_modules/nodetime/node_modules/nodetime-native/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/hubert/.meteorite/packages/nodetime/subhog/meteor-nodetime/71c155845b4d0c99ba471d1498d113cef499dbd6/.npm/node_modules/nodetime/node_modules/nodetime-native/index.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

After that, tests proceed normally. The nodetime package works smoothly in normal app run.

**Comment by arunoda** [comment]
This is expected. You need to rebuild nodetime after node version change.

On Wednesday, June 19, 2013, subhog wrote:

> When I run laika commmand, I'm greeted with four such error messages:
> 
> nodetime v0.8.12 error: [Error: Module version mismatch. Expected 11, got 1.] Error: Module version mismatch. Expected 11, got 1.
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at bindings (/Users/hubert/.meteorite/packages/nodetime/subhog/meteor-nodetime/71c155845b4d0c99ba471d1498d113cef499dbd6/.npm/node_modules/nodetime/node_modules/nodetime-native/node_modules/bindings/bindings.js:76:44)
>     at Object.<anonymous> (/Users/hubert/.meteorite/packages/nodetime/subhog/meteor-nodetime/71c155845b4d0c99ba471d1498d113cef499dbd6/.npm/node_modules/nodetime/node_modules/nodetime-native/index.js:1:99)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
> 
> After that, tests proceed normally. The nodetime package works smoothly in
> normal app run.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/laika/issues/18
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda
