### ISSUE TITLE
Using HTML reporter causes crash

### ISSUE THREAD

**Issue by cdcme** [arunoda/laika#24]
``` bash
laika -u bdd -R html

  injecting laika...
  loading phantomjs...
  loading initial app pool...
  cleaning up injected code


/Users/carlodicelico/.nvm/v0.10.12/lib/node_modules/laika/node_modules/mocha/lib/reporters/html.js:194
    , div = document.createElement('div')
            ^
ReferenceError: document is not defined
    at fragment (/Users/carlodicelico/.nvm/v0.10.12/lib/node_modules/laika/node_modules/mocha/lib/reporters/html.js:194:13)
    at new HTML (/Users/carlodicelico/.nvm/v0.10.12/lib/node_modules/laika/node_modules/mocha/lib/reporters/html.js:51:14)
    at Mocha.run (/Users/carlodicelico/.nvm/v0.10.12/lib/node_modules/laika/node_modules/mocha/lib/mocha.js:310:18)
    at AppPool.onAppPoolReady (/Users/carlodicelico/.nvm/v0.10.12/lib/node_modules/laika/bin/_laika:91:26)
    at AppPool.EventEmitter.emit (events.js:92:17)
    at App.createInitialPool (/Users/carlodicelico/.nvm/v0.10.12/lib/node_modules/laika/lib/app_pool.js:25:12)
    at App.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (/Users/carlodicelico/.nvm/v0.10.12/lib/node_modules/laika/lib/app.js:48:14)
    at Socket.EventEmitter.emit (events.js:117:20)
    at Socket.<anonymous> (_stream_readable.js:736:14)
```

**Comment by arunoda** [comment]
Yes. It is not working for somehow. Need to know why? 
I've never used it before.
