### ISSUE TITLE
timeout exceeded

### ISSUE THREAD

**Issue by lfergon** [arunoda/laika#48]
Hi, I have a problem with Laika: node version 0.10.15, I have update phantomjs.
$> laika -d -t 10000
Doen´t matter timeout that I pass to Laika, always fail.
  Error: timeout of 10000ms exceeded
      at null.<anonymous> (/opt/local/lib/node_modules/laika/node_modules/mocha/lib/runnable.js:165:14)
      at Timer.listOnTimeout [as ontimeout](timers.js:110:15)

**Comment by lacco** [comment]
Could you please post your test that is failing? Perhaps you just forgot to call `done()` ?

**Comment by mfaerevaag** [comment]
I'm getting the same problem!

`node v0.10.24`
`laika v0.3.2`
`phantomjs v1.9.2-6`

I'm using the same tests as in the [hello-laika example repo](https://github.com/arunoda/hello-laika/blob/master/tests/posts.js), only rewritten in coffee with a different collection.

```
# tests/players_test.coffee

assert = require 'assert'

suite 'Players', ->
  test 'in the server', (done, server) ->
    server.eval ->
      Players.insert name: 'moby'
      players = Players.find().fetch()
      emit 'players', players

    server.once 'players', (players) ->
      assert.equal players.length, 1
      done()

  test 'using both client and the server', (done, server, client) ->
    server.eval ->
      Players.find().observe
        added: (player) ->
          emit 'player', player

    .once 'player', (player) ->
      assert.equal player.name, 'moby'
      done()

    server.eval  ->
      Players.insert name: 'moby'

  test 'using two clients', (done, server, client1, client2) ->
    client1.eval ->
      Players.find().observe
        added: (player) ->
          emit 'player', player

      emit 'done'

    .once 'player', (player) ->
      assert.equal player.name, 'moby'
      done()

    .once 'done', ->
      client2.eval ->
        Players.insert name: 'moby'
```

My output from `laika -V`:

```
[laika log] accepting the following extensions: (js|coffee)

  injecting laika...
  loading phantomjs...
[app touch log] 
[app touch log] Stand back while Meteorite does its thing
[app touch log]   Package npm has been ignored because it has been manually installed in /packages

[app touch log] 
[app touch log] Done installing smart packages
[app touch log] 
Ok, everything's ready. Here comes Meteor!

[app touch log] [[[[[ ~/IT/Dev/BBP/CoSound/Sound-Duel/app ]]]]]

  loading initial app pool...
[app touch log] => Meteor server running on: http://localhost:24868/
[laika log] using nodejs bin(from meteorite): /Users/markus/.meteor/tools/09b63f1ed5/bin/node
[laika log] using nodejs bin(from meteorite): /Users/markus/.meteor/tools/09b63f1ed5/bin/node
[server log] laika code injected and listening on: 12841
[server log] Refreshing db..
[server log] #Questions: 5
[server log] #Sounds: 15
[server log] LISTENING
[laika log] adding compiler module: coffee-script
[laika log] adding test file: /Users/markus/IT/Dev/BBP/CoSound/Sound-Duel/app/tests/players_test.coffee
1..3
[server log] laika code injected and listening on: 24392
[server log] Refreshing db..
#Questions: 5
#Sounds: 15
LISTENING
[laika log] start running test
[laika log] using nodejs bin(from meteorite): /Users/markus/.meteor/tools/09b63f1ed5/bin/node
[laika log] running test
[laika log] test completed
[laika log] closing app
ok 1 Players in the server
[laika log] start running test
[laika log] using nodejs bin(from meteorite): /Users/markus/.meteor/tools/09b63f1ed5/bin/node
[laika log] running test
not ok 2 Players using both client and the server
  SyntaxError: Unexpected token {
      at Object.parse (native)
      at Socket.onData (app/server/meteor-suite-server.js:15:23)
      at Socket.EventEmitter.emit (events.js:95:17)
      at Socket.<anonymous> (_stream_readable.js:746:14)
      at Socket.EventEmitter.emit (events.js:92:17)
      at emitReadable_ (_stream_readable.js:408:10)
      at emitReadable (_stream_readable.js:404:5)
      at readableAddChunk (_stream_readable.js:165:9)
      at Socket.Readable.push (_stream_readable.js:127:10)
      at TCP.onread (net.js:526:21)
[laika log] start running test
[laika log] using nodejs bin(from meteorite): /Users/markus/.meteor/tools/09b63f1ed5/bin/node
phantom stderr: 2014-01-16 14:32:09.269 phantomjs[62908:507] CoreText performance note: Client called CTFontCreateWithName() using name "Helvetica Neue" and got font with PostScript name "HelveticaNeue". For best performance, only use PostScript names when calling this API.
2014-01-16 14:32:09.270 phantomjs[62908:507] CoreText performance note: Set a breakpoint on CTFontLogSuboptimalRequest to debug.

[phantom log] 2014-01-16 14:32:09.269 phantomjs[62908:507] CoreText performance note: Client called CTFontCreateWithName() using name "Helvetica Neue" and got font with PostScript name "HelveticaNeue". For best performance, only use PostScript names when calling this API.
2014-01-16 14:32:09.270 phantomjs[62908:507] CoreText performance note: Set a breakpoint on CTFontLogSuboptimalRequest to debug.
[client log] Started at: http://localhost:18981/
[server log] laika code injected and listening on: 27903
[laika log] running test
[server log] laika code injected and listening on: 26884
[server log] Refreshing db..
[server log] laika code injected and listening on: 19855
[server log] Refreshing db..
[server log] Refreshing db..
[server log] #Questions: 5
[server log] #Sounds: 15
[server log] LISTENING
[server log] #Questions: 5
[server log] #Sounds: 15
[server log] LISTENING
[server log] #Questions: 5
[server log] #Sounds: 15
[server log] LISTENING
not ok 3 Players using two clients
  Error: timeout of 5000ms exceeded
      at null.<anonymous> (/usr/local/lib/node_modules/laika/node_modules/mocha/lib/runnable.js:175:14)
      at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
# tests 3
# pass 1
# fail 2
  cleaning up injected code
```

Note: It hangs on 'cleaing up injected code' and never exits.

**Comment by zhaoyou** [comment]
I'm getting the same problem!
node.js v0.10.22
meteor 0.8.0.1

**Comment by chompomonim** [comment]
Same here. Meteor 0.8.1, Node v0.10.25

**Comment by fpoirier1** [comment]
+1

**Comment by magee** [comment]
+1

**Comment by AdamBrodzinski** [comment]
+1 using coffeescript in meteor and tests on 0.8.1.2

Getting either a timeout, or `SyntaxError: Unexpected token {`, sometime both.

If I downgrade `.meteor/release` to `0.8.0.1` and run mongod using just `mongod` it will pass every few tries.

However, if i'm running `0.8.0.1` and use `mongod --smallfiles --noprealloc --nojournal` then it passes every time (or at least 15x in a row).

The bummer is that `--smallfiles --noprealloc --nojournal` is broke in the newest release :frowning: 
https://github.com/arunoda/laika/issues/117

**Comment by teonimesic** [comment]
+1 using coffeescript in meteor 0.8.1.3. Increasing timeout to 10000ms worked for me, at least most of the times.

**Comment by AdamBrodzinski** [comment]
@teonimesic did you have to use the `--smallfiles --noprealloc --nojournal` flags with `mongod`? I tried bumping up mine to 20000ms with no luck.

**Comment by apendua** [comment]
The problem you are experiencing is in fact not a **BUG** but a test written improperly. If you tried to debug a little deeper within **laika** source code, you would notice that the `SyntaxError: Unexpected token {` is thrown by the `JSON.parse` being feed with a `JSON` string of the form `{...}{...}`.

The reason this is happening is how the `server.eval` routine works. It sends a `JSON` describing the code which should be executed (on the server) through a web socket. If you happen to call these method twice in a row (at the same time), the two `JSONs` will get concatenated and will be sent as a single message. The server will then try to parse the received string with no luck.

Of course this behavior is a little unexpected and probably it needs to be fixed. However, I think that calling `server.eval` for the second time without waiting for the result of the first action is something we should try to avoid in our tests. Supposing that there's some test logic that requires multiple calls to `server.eval`, I would encourage you to use `promises`.

**Comment by AdamBrodzinski** [comment]
Ah good catch @apendua ! :beers: 

It turns out I didn't actually need to use two separate evals anyhow. That explains the occasional syntax error. I'm still having timeout issues with 0.8.1.x though. Are you experiencing the same?

**Comment by apendua** [comment]
@AdamBrodzinski I haven't tested with laika on 0.8.1.x, so I cannot tell. But you can try using my very own [fork](https://github.com/apendua/laika), `devel` branch where I have already fixed some stuff related to `setTimeout` BUG in `phantomjs`. This problem actually prevented `waitForDOM` to work as expected, so if this may be a source of your problems.
