### ISSUE TITLE
Not working after update to Meteor 0.6.5

### ISSUE THREAD

**Issue by wizonesolutions** [arunoda/laika#51]
I'm getting the following output. I have a couple migrations that wind up running since it's a fresh copy of the app, but they shouldn't be doing anyhting. I think the `optimist` and `ECONNREFUSED` problems are more relevant, although I might be wrong.

```
$ laika -d -t 20000

  injecting laika...
  loading phantomjs...
[app touch log]
[app touch log] Stand back while Meteorite does its thing
[app touch log]
Done installing smart packages
[app touch log]
[app touch log] Ok, everything's ready. Here comes Meteor!

[app touch log] [[[[[ ~/meteor/apps/spendflow ]]]]]

  loading initial app pool...
[app touch log] => Meteor server running on: http://localhost:21454/
[server log] Oops, looks like the Segment.io API key is missing! Analytics won't work until you fix that.
[server log] laika code injected and listening on: 18695
[server log] Running migration: 20130630_iso_dates
[server log] ====== INCOMES ======
[server log] ====== EXPENSES ======
[server log] Running migration: 20130630_iso_dates_2
[server log] ====== INCOMES ======
[server log] ====== EXPENSES ======
[server log] Running migration: 20130630_payment_metadata
[server log] Incomes...
[server log] Expenses...
[server log] Migration complete.
[server log]
[server log] /Users/kevin/.meteor/tools/4010e5731d/lib/node_modules/fibers/future.js:173
[server log]                                            throw(ex);
                [server log]                                  ^
[server log] Error: ENOENT, no such file or directory
    at Argv (/Users/kevin/.meteor/tools/4010e5731d/lib/node_modules/optimist/index.js:22:29)
    at Object.main (packages/webapp/webapp_server.js:428)
    at /Users/kevin/meteor/apps/spendflow/.meteor/local/build/programs/server/boot.js:180:27
[server log] Oops, looks like the Segment.io API key is missing! Analytics won't work until you fix that.
1..1
[server log] laika code injected and listening on: 13393
[server log] Running migration: 20130630_iso_dates
====== INCOMES ======
====== EXPENSES ======
Running migration: 20130630_iso_dates_2
[server log] ====== INCOMES ======
====== EXPENSES ======
not ok 1 Basic setup accounting.js exists
  Error: connect ECONNREFUSED
```

And my test looks like

`$ cat tests/spendflow.test.js`

``` javascript
var assert = require('assert');
var _ = require('underscore');

suite('Basic setup', function () {
  test('accounting.js exists', function (done, server, client) {
    client.eval(function () {
      emit('done', accounting);
    }).once('done', function (accountingObject) {
        if (! accountingObject) {
          // Make it fail test without ReferenceError
          accountingObject = null;
        }
        assert.equal(_.isObject(accountingObject), true);
        done();
      });
  });
});
```

**Comment by arunoda** [comment]
can you run your app?

**Comment by wizonesolutions** [comment]
Yeah, my app is fine. It only does that after `laika` injects the code, and it stops doing it once `laika` removes it.

**Comment by arunoda** [comment]
Can you please update to `0.3.0` it cleans injected files well. Not sure it is a fix though.

**Comment by wizonesolutions** [comment]
Works again now :)
