### ISSUE TITLE
Laika hangs when an error is present

### ISSUE THREAD

**Issue by et** [arunoda/laika#63]
If an error is present in the app, `laika` should fail or at least be somewhat verbose about the error.

``` bash
~/t/todos ❯❯❯ laika

  injecting laika...
  loading phantomjs...
  loading initial app pool...
^C  cleaning up injected code

~/t/todos ❯❯❯ laika -V
[laika log] accepting the following extensions: (js)

  injecting laika...
  loading phantomjs...
[app touch log] [[[[[ ~/tmp/todos ]]]]]

[app touch log] => Meteor server running on: http://localhost:12060/
  loading initial app pool...
[laika log] using nodejs bin(from meteor): /Users/et/.meteor/tools/a80b2d5689/bin/node
[server log]
[server log] /Users/et/tmp/todos/.meteor/local/build/programs/server/boot.js:185
}).run();
   ^
[server log] ReferenceError: require is not defined
    at app/node_modules/should/lib/eql.js:3:12
    at app/node_modules/should/lib/eql.js:98:3
    at /Users/et/tmp/todos/.meteor/local/build/programs/server/boot.js:154:10
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/et/.meteor/tools/a80b2d5689/lib/node_modules/underscore/underscore.js:79:11)
    at /Users/et/tmp/todos/.meteor/local/build/programs/server/boot.js:81:5
```

**Comment by joernroeder** [comment]
same issue here…

**Comment by Ceasar** [comment]
+1

**Comment by arunoda** [comment]
I'll starting to work on the next major version of Laika next week with
fixing a lot of bugs. I'll update more on this. patches are welcome :)

On Thu, Feb 6, 2014 at 6:26 AM, Ceasar Bautista notifications@github.comwrote:

> +1
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/laika/issues/63#issuecomment-34281201
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda
