### ISSUE TITLE
laika errors out on pending tests

### ISSUE THREAD

**Issue by jagill** [arunoda/laika#65]
When laika encounters a pending test (one with no test fn), it errors out:

```
jag@coati:/tmp/laikaTest$ laika --ui bdd -V
[laika log] accepting the following extensions: (js)

  injecting laika...
  loading phantomjs...
[app touch log] [[[[[ /private/tmp/laikaTest ]]]]]

[app touch log] => Meteor server running on: http://localhost:16538/
  loading initial app pool...
[laika log] using nodejs bin(from meteor): /Users/jag/.meteor/tools/bebd881297/bin/node
[laika log] using nodejs bin(from meteor): /Users/jag/.meteor/tools/bebd881297/bin/node
[server log] laika code injected and listening on: 22815
[server log] LISTENING
[laika log] adding test file: /private/tmp/laikaTest/tests/appTest.js
1..1
[server log] laika code injected and listening on: 15604
[server log] LISTENING
[laika log] start running test
not ok 1 Test test should ignore pending tests
  TypeError: Cannot read property 'length' of undefined
      at Context.mockTest (/usr/local/share/npm/lib/node_modules/laika/lib/test_logic.js:21:18)
      at Test.Runnable.run (/usr/local/share/npm/lib/node_modules/laika/node_modules/mocha/lib/runnable.js:194:15)
      at Runner.runTest (/usr/local/share/npm/lib/node_modules/laika/node_modules/mocha/lib/runner.js:352:10)
      at Runner.runTests.next (/usr/local/share/npm/lib/node_modules/laika/node_modules/mocha/lib/runner.js:398:12)
      at next (/usr/local/share/npm/lib/node_modules/laika/node_modules/mocha/lib/runner.js:278:14)
      at Runner.hooks (/usr/local/share/npm/lib/node_modules/laika/node_modules/mocha/lib/runner.js:287:7)
      at next (/usr/local/share/npm/lib/node_modules/laika/node_modules/mocha/lib/runner.js:234:23)
      at Runner.hook (/usr/local/share/npm/lib/node_modules/laika/node_modules/mocha/lib/runner.js:255:5)
      at process.startup.processNextTick.process._tickCallback (node.js:244:9)
# tests 1
# pass 0
# fail 1
  cleaning up injected code
```

A test file that fails is at https://gist.github.com/jagill/7199376

**Comment by arunoda** [comment]
You must need to pass a callback to it.
